name: triangle_splatting
channels:
    - nvidia
    - conda-forge
    - defaults
dependencies:
    - cuda=12.6
    - python=3.11
    - pip:
        - torch==2.4.0
        - torchvision==0.19.0
        - tqdm
        - plyfile
        - open3d
        - lpips
        - mediapy
        - opencv-python
    
